import { writeAudioBufferToWav } from "./audioGenerator"
import { renderNotesToAudioBuffer } from "./audioRenderer"
import { generateNotes } from "./textToNotes"

async function main() {
  const inputString = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac ultrices libero. Cras eu quam sagittis, pharetra metus sit amet, lobortis leo. Mauris eget mi leo. Pellentesque vitae sapien augue. Duis lacinia ante in elit interdum ullamcorper. Pellentesque vestibulum eget magna blandit feugiat. Proin et ligula convallis, tincidunt purus ut, consectetur tellus. Quisque laoreet ligula eu nisi scelerisque, blandit gravida velit pulvinar. Vestibulum at ante non arcu laoreet vulputate. Proin lectus nisi, imperdiet quis nunc in, viverra ullamcorper lacus. Aliquam nec aliquam ex. In consequat elementum nibh, non tincidunt neque aliquam mollis. Nullam odio purus, rutrum ut luctus eu, venenatis nec neque. Phasellus enim enim, scelerisque sit amet placerat vel, ultrices eu elit.
Morbi lobortis ullamcorper risus, id iaculis leo convallis eget. Sed sollicitudin metus in vulputate maximus. Praesent id facilisis lacus. Donec sed faucibus nisl, a mattis nunc. Sed ac ullamcorper lorem. Vestibulum quis est in mi aliquam elementum in in ipsum. Phasellus pharetra ornare rutrum. Nunc at dictum dui. Curabitur scelerisque arcu nec aliquet commodo. Nullam facilisis sollicitudin velit ut pulvinar. Sed ut posuere velit, in hendrerit arcu. Phasellus ullamcorper risus hendrerit sodales varius. Sed fringilla pretium venenatis. Morbi eget consequat augue. Etiam consequat, mauris quis fringilla suscipit, libero lacus pharetra lacus, id aliquet mi felis nec sapien. Maecenas et magna scelerisque sem convallis rhoncus in quis justo.
Quisque vitae nisi venenatis elit gravida faucibus tincidunt at dui. Aenean aliquam dolor orci, at aliquet risus rhoncus scelerisque. Donec tristique, arcu id pretium varius, massa est mollis mauris, ac iaculis mi sem a est. Vestibulum diam orci, scelerisque et efficitur non, interdum sit amet leo. Mauris efficitur placerat sapien at volutpat. Duis sagittis posuere quam, sed venenatis augue auctor tincidunt. Quisque sagittis tempus pharetra. Fusce molestie blandit lectus, non accumsan tellus varius iaculis. Quisque lacinia blandit mauris in interdum. Fusce ullamcorper lacinia risus vitae vestibulum. Nunc eros nisl, pellentesque vel ultrices et, lacinia a massa. In eget dictum nisi, sit amet aliquet metus. Donec ac justo sit amet lectus tincidunt egestas vel sit amet nisi. Nunc volutpat tellus sit amet mattis tempus. Nam faucibus felis vel metus rutrum ultrices.
Etiam ultricies quam sem, non porttitor mauris interdum nec. Suspendisse potenti. Mauris laoreet leo felis, ut imperdiet dolor auctor in. Donec at maximus nibh. Duis non sagittis metus, ut viverra ante. Nam eleifend eros lorem, nec interdum elit laoreet in. Sed interdum odio non diam viverra, et ornare velit posuere. Nam dapibus sapien eget magna molestie, sed accumsan ipsum suscipit. Vivamus facilisis, leo a tempus vulputate, lectus eros pharetra augue, vel suscipit arcu sapien vitae velit. In rutrum est enim, a pharetra orci sollicitudin non. Duis aliquam mauris et dolor rutrum accumsan. Sed rutrum, lorem vel bibendum viverra, nibh purus gravida metus, at aliquet neque risus quis neque. Maecenas tincidunt, mi eget consequat imperdiet, turpis leo rutrum erat, in tristique massa quam a nunc. Vestibulum ornare libero et sem volutpat venenatis. Nulla efficitur ultricies lorem vel fermentum. Aenean eu venenatis lacus, ut vehicula tortor.
Quisque egestas eget orci a rhoncus. Morbi lobortis, leo elementum ultrices finibus, mauris lacus rutrum magna, vehicula ultricies orci velit vitae ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla cursus magna dui, vitae pretium sapien vulputate eget. Donec hendrerit risus vel lacus accumsan vehicula. Etiam erat neque, tincidunt vitae enim quis, egestas scelerisque magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam venenatis volutpat laoreet. Proin tempor lobortis congue. Maecenas semper scelerisque nulla ut mattis. Suspendisse commodo libero in ante fermentum, non tincidunt diam facilisis. Phasellus vel sapien felis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac ultrices libero. Cras eu quam sagittis, pharetra metus sit amet, lobortis leo. Mauris eget mi leo. Pellentesque vitae sapien augue. Duis lacinia ante in elit interdum ullamcorper. Pellentesque vestibulum eget magna blandit feugiat. Proin et ligula convallis, tincidunt purus ut, consectetur tellus. Quisque laoreet ligula eu nisi scelerisque, blandit gravida velit pulvinar. Vestibulum at ante non arcu laoreet vulputate. Proin lectus nisi, imperdiet quis nunc in, viverra ullamcorper lacus. Aliquam nec aliquam ex. In consequat elementum nibh, non tincidunt neque aliquam mollis. Nullam odio purus, rutrum ut luctus eu, venenatis nec neque. Phasellus enim enim, scelerisque sit amet placerat vel, ultrices eu elit.
Morbi lobortis ullamcorper risus, id iaculis leo convallis eget. Sed sollicitudin metus in vulputate maximus. Praesent id facilisis lacus. Donec sed faucibus nisl, a mattis nunc. Sed ac ullamcorper lorem. Vestibulum quis est in mi aliquam elementum in in ipsum. Phasellus pharetra ornare rutrum. Nunc at dictum dui. Curabitur scelerisque arcu nec aliquet commodo. Nullam facilisis sollicitudin velit ut pulvinar. Sed ut posuere velit, in hendrerit arcu. Phasellus ullamcorper risus hendrerit sodales varius. Sed fringilla pretium venenatis. Morbi eget consequat augue. Etiam consequat, mauris quis fringilla suscipit, libero lacus pharetra lacus, id aliquet mi felis nec sapien. Maecenas et magna scelerisque sem convallis rhoncus in quis justo.
Quisque vitae nisi venenatis elit gravida faucibus tincidunt at dui. Aenean aliquam dolor orci, at aliquet risus rhoncus scelerisque. Donec tristique, arcu id pretium varius, massa est mollis mauris, ac iaculis mi sem a est. Vestibulum diam orci, scelerisque et efficitur non, interdum sit amet leo. Mauris efficitur placerat sapien at volutpat. Duis sagittis posuere quam, sed venenatis augue auctor tincidunt. Quisque sagittis tempus pharetra. Fusce molestie blandit lectus, non accumsan tellus varius iaculis. Quisque lacinia blandit mauris in interdum. Fusce ullamcorper lacinia risus vitae vestibulum. Nunc eros nisl, pellentesque vel ultrices et, lacinia a massa. In eget dictum nisi, sit amet aliquet metus. Donec ac justo sit amet lectus tincidunt egestas vel sit amet nisi. Nunc volutpat tellus sit amet mattis tempus. Nam faucibus felis vel metus rutrum ultrices.
Etiam ultricies quam sem, non porttitor mauris interdum nec. Suspendisse potenti. Mauris laoreet leo felis, ut imperdiet dolor auctor in. Donec at maximus nibh. Duis non sagittis metus, ut viverra ante. Nam eleifend eros lorem, nec interdum elit laoreet in. Sed interdum odio non diam viverra, et ornare velit posuere. Nam dapibus sapien eget magna molestie, sed accumsan ipsum suscipit. Vivamus facilisis, leo a tempus vulputate, lectus eros pharetra augue, vel suscipit arcu sapien vitae velit. In rutrum est enim, a pharetra orci sollicitudin non. Duis aliquam mauris et dolor rutrum accumsan. Sed rutrum, lorem vel bibendum viverra, nibh purus gravida metus, at aliquet neque risus quis neque. Maecenas tincidunt, mi eget consequat imperdiet, turpis leo rutrum erat, in tristique massa quam a nunc. Vestibulum ornare libero et sem volutpat venenatis. Nulla efficitur ultricies lorem vel fermentum. Aenean eu venenatis lacus, ut vehicula tortor.
Quisque egestas eget orci a rhoncus. Morbi lobortis, leo elementum ultrices finibus, mauris lacus rutrum magna, vehicula ultricies orci velit vitae ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla cursus magna dui, vitae pretium sapien vulputate eget. Donec hendrerit risus vel lacus accumsan vehicula. Etiam erat neque, tincidunt vitae enim quis, egestas scelerisque magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam venenatis volutpat laoreet. Proin tempor lobortis congue. Maecenas semper scelerisque nulla ut mattis. Suspendisse commodo libero in ante fermentum, non tincidunt diam facilisis. Phasellus vel sapien felis.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac ultrices libero. Cras eu quam sagittis, pharetra metus sit amet, lobortis leo. Mauris eget mi leo. Pellentesque vitae sapien augue. Duis lacinia ante in elit interdum ullamcorper. Pellentesque vestibulum eget magna blandit feugiat. Proin et ligula convallis, tincidunt purus ut, consectetur tellus. Quisque laoreet ligula eu nisi scelerisque, blandit gravida velit pulvinar. Vestibulum at ante non arcu laoreet vulputate. Proin lectus nisi, imperdiet quis nunc in, viverra ullamcorper lacus. Aliquam nec aliquam ex. In consequat elementum nibh, non tincidunt neque aliquam mollis. Nullam odio purus, rutrum ut luctus eu, venenatis nec neque. Phasellus enim enim, scelerisque sit amet placerat vel, ultrices eu elit.
Morbi lobortis ullamcorper risus, id iaculis leo convallis eget. Sed sollicitudin metus in vulputate maximus. Praesent id facilisis lacus. Donec sed faucibus nisl, a mattis nunc. Sed ac ullamcorper lorem. Vestibulum quis est in mi aliquam elementum in in ipsum. Phasellus pharetra ornare rutrum. Nunc at dictum dui. Curabitur scelerisque arcu nec aliquet commodo. Nullam facilisis sollicitudin velit ut pulvinar. Sed ut posuere velit, in hendrerit arcu. Phasellus ullamcorper risus hendrerit sodales varius. Sed fringilla pretium venenatis. Morbi eget consequat augue. Etiam consequat, mauris quis fringilla suscipit, libero lacus pharetra lacus, id aliquet mi felis nec sapien. Maecenas et magna scelerisque sem convallis rhoncus in quis justo.
Quisque vitae nisi venenatis elit gravida faucibus tincidunt at dui. Aenean aliquam dolor orci, at aliquet risus rhoncus scelerisque. Donec tristique, arcu id pretium varius, massa est mollis mauris, ac iaculis mi sem a est. Vestibulum diam orci, scelerisque et efficitur non, interdum sit amet leo. Mauris efficitur placerat sapien at volutpat. Duis sagittis posuere quam, sed venenatis augue auctor tincidunt. Quisque sagittis tempus pharetra. Fusce molestie blandit lectus, non accumsan tellus varius iaculis. Quisque lacinia blandit mauris in interdum. Fusce ullamcorper lacinia risus vitae vestibulum. Nunc eros nisl, pellentesque vel ultrices et, lacinia a massa. In eget dictum nisi, sit amet aliquet metus. Donec ac justo sit amet lectus tincidunt egestas vel sit amet nisi. Nunc volutpat tellus sit amet mattis tempus. Nam faucibus felis vel metus rutrum ultrices.
Etiam ultricies quam sem, non porttitor mauris interdum nec. Suspendisse potenti. Mauris laoreet leo felis, ut imperdiet dolor auctor in. Donec at maximus nibh. Duis non sagittis metus, ut viverra ante. Nam eleifend eros lorem, nec interdum elit laoreet in. Sed interdum odio non diam viverra, et ornare velit posuere. Nam dapibus sapien eget magna molestie, sed accumsan ipsum suscipit. Vivamus facilisis, leo a tempus vulputate, lectus eros pharetra augue, vel suscipit arcu sapien vitae velit. In rutrum est enim, a pharetra orci sollicitudin non. Duis aliquam mauris et dolor rutrum accumsan. Sed rutrum, lorem vel bibendum viverra, nibh purus gravida metus, at aliquet neque risus quis neque. Maecenas tincidunt, mi eget consequat imperdiet, turpis leo rutrum erat, in tristique massa quam a nunc. Vestibulum ornare libero et sem volutpat venenatis. Nulla efficitur ultricies lorem vel fermentum. Aenean eu venenatis lacus, ut vehicula tortor.
Quisque egestas eget orci a rhoncus. Morbi lobortis, leo elementum ultrices finibus, mauris lacus rutrum magna, vehicula ultricies orci velit vitae ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla cursus magna dui, vitae pretium sapien vulputate eget. Donec hendrerit risus vel lacus accumsan vehicula. Etiam erat neque, tincidunt vitae enim quis, egestas scelerisque magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam venenatis volutpat laoreet. Proin tempor lobortis congue. Maecenas semper scelerisque nulla ut mattis. Suspendisse commodo libero in ante fermentum, non tincidunt diam facilisis. Phasellus vel sapien felis.
`

  const sampleRate = 44100
  const outputFileName = "generated_music_from_text.wav"

  try {
    console.log(`Generating audio notes from input string: "${inputString}"...`)
    const notes = generateNotes(inputString)
    console.log("Audio notes generated. Rendering to audio buffer...")

    const audioBuffer = await renderNotesToAudioBuffer(notes, sampleRate)
    console.log("Audio buffer generated. Saving to WAV file...")

    await writeAudioBufferToWav(audioBuffer, outputFileName)
    console.log(`Successfully created '${outputFileName}'`)
  } catch (error) {
    console.error("Failed to generate or write WAV file:", error)
  }
}

main()
